### ISSUE TITLE
Artefact Evaluation support

### ISSUE THREAD

**Issue by acocac** [alan-turing-institute/climate-informatics-2024-ae#6]
### Summary Sentence
Support activities to facilitate the introduction and on-boarding to authors and reviewers that participate in the Artefact Evaluation process.

### What needs to be done?

- [x] #9 
- [ ] On-boarding session
- [ ] Closure session

See also:
- alan-turing-institute/climate-informatics-2024-ae#1

**Comment by cassgvp** [comment]
Informative session needs to be post-meeting. We cannot support even informal gatherings which are exclusive to some participants and distracts from the main body of the meeting.

@lelle notes we can continue to use HyHive for 2 weeks after the meeting - can hold it there.

**Comment by dorchard** [comment]
Okay I understand. So perhaps on the Wednesday afternoon then? Or do something remote?

**Comment by acocac** [comment]
> Okay I understand. So perhaps on the Wednesday afternoon then? Or do something remote?

@dorchard I think remote should work - While most authors will attend in-person the CI2024 conference, there are still others joining virtually.  We can formally introduce the artefact evaluation at the end of the panel as we did last year for the Reproducibility Challenge.

**Comment by dorchard** [comment]
Okay that sounds good. Should I put a slide or two together for it?

**Comment by acocac** [comment]
> Okay that sounds good. Should I put a slide or two together for it?

A single slide should be fine. Sharing below the promo slide of the Reproducibility Challenge I presented at the end of the panel last year:
https://docs.google.com/presentation/d/1rmLJsI5FNdCd84lpNZxvHIL_sq6GgtTZzmgrYHPCbE8/edit?usp=sharing
