### ISSUE TITLE
Artefact Evaluation website

### ISSUE THREAD

**Issue by acocac** [alan-turing-institute/climate-informatics-2024-ae#7]
### Summary Sentence
A website to facilitate the navigation of the context, scope, timelines and others of the AE process.

### What needs to be done?
- [x] Choose the most convenient template e.g. [JupyterBook](https://jupyterbook.org), [Docusaurus](https://docusaurus.io/)
- [x] Set a structure i.e. sections of the website

See also:
- alan-turing-institute/climate-informatics-2024-ae#1

**Comment by cassgvp** [comment]
Suggestion for materials to exist as a page(s) from the CI2024 website. @cassgvp to set up and make sure everyone has maintainer access

**Comment by acocac** [comment]
I've forked the repository to propose a prototype of the website using Jupyter Book. Find the live version below:

https://acocac.github.io/climate-informatics-2024-ae/intro.html

Thoughts are welcome!

**Comment by dorchard** [comment]
I like it!
