### ISSUE TITLE
Informative Session

### ISSUE THREAD

**Issue by acocac** [alan-turing-institute/climate-informatics-2024-ae#9]
### Summary Sentence
The introductory section, date TBC, will cover the AE process, expectations, timeline, technologies and useful resources. 

### What needs to be done?
- [x] Slides
- [x] Zoom registration webpage
- [x] #12
- [ ] Reviewers form (recruitment)

### Who can help?

Anyone

**Comment by dorchard** [comment]
I guess it would make sense to have a Doodle poll amongst us and then we can tell the authors the time it will be (end of May?) and if some cannot make it we can record it and link them to the recording? Or we can try to do a Doodle with all the authors too and pre-maximise the number that can attend live?

**Comment by acocac** [comment]
A first draft of the slides is available at the [Google Drive Folder of CI2024](https://docs.google.com/presentation/d/1VlP7IkRVb22Q_wWjeuSW0tvl6TC-3tEJk0TacHHw1x8/edit?usp=sharing)
